<a href="https://colab.research.google.com/github/OuEmily/Bin_coding/blob/main/bin_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Задача 1

In [ ]:
import numpy as np

In [ ]:
#Функция для создания образующей матрицы для повторяющихся кодов [rk,k]
def create_G_for_repetitive_code(r, k):

  G = np.zeros((k, r*k), dtype=int)
  for i in range(k):
    for j in range(r):
      G[i, i*r + j] = 1
  return G

# Пример использования:
r = 3
k = 1

G = create_G_for_repetitive_code(r, k)
print("Порождающая матрица G:\n", G)

Порождающая матрица G:
 [[1 1 1]]


In [ ]:
#Функция для кодирования сообщений с помощью порождающей матрицы G

def encode_message(message, G):

    return np.dot(message, G) % 2

#Прример использования

#G = np.array([[1, 0, 0, 1, 1, 0], [0, 1, 0, 0, 1, 1], [0, 0, 1, 1, 0, 1]])

message = np.array([1, 0, 1])

encoded_message = encode_message(message, G)

print("Исходное сообщение:", message)
print("Закодированное сообщение:", encoded_message)


Исходное сообщение: [1 0 1]
Закодированное сообщение: [1 0 1 0 1 1]


In [ ]:
#Функция для проверки ошибок с помощью проверочной матрицы H

def check_for_errors(codeword, H):
    err = np.dot(codeword, H.T) % 2
    return err

#Пример использования
#H = np.array([[1, 1, 0, 1, 0, 0], [0, 1, 1, 0, 1, 0], [1, 0, 1, 0, 0, 1]])
codeword = np.array([1, 0, 1, 1, 1, 0])
errors = check_for_errors(codeword, H)
print("Проверка:", errors)


Проверка: [0 0 0]


In [ ]:
#Функция для исправления ошибок
def correct_errors(codeword, H):

    errors = check_for_errors(codeword, H)

    if np.all(errors == 0):
        return codeword

    for i in range(H.shape[1]):
        if np.array_equal(errors, H[:, i]):
            codeword[i] = (codeword[i] + 1) % 2
            break

    return codeword

In [ ]:
#Пример использования
codeword_with_error = np.array([1, 0, 1, 1, 0, 0])
print("Сообщение с ошибкой:", codeword_with_error)
corrected_codeword = correct_errors(codeword_with_error, H)

#print("Сообщение с ошибкой:", codeword_with_error)
print("Исправленное сообщение:", corrected_codeword)


Сообщение с ошибкой: [1 0 1 1 0 0]
Исправленное сообщение: [1 0 1 1 1 0]


### Доп. задание к заданию 1

In [ ]:
#Функция для создания проверочной матрицы из порождающей
def create_H_from_G(G):

  k, n = G.shape
  P = G[:, k:]
  I_r = np.eye(n - k, dtype=int)
  H = np.concatenate((P.T, I_r), axis=1)

  return H


# Пример использования:
G = np.array([[1, 0, 0, 1, 1, 0],
              [0, 1, 0, 0, 1, 1],
              [0, 0, 1, 1, 0, 1]])

H = create_H_from_G(G)
print("Порождающая матрица G: \n", G)
print("Проверочная матрица H: \n", H)


Порождающая матрица G: 
 [[1 0 0 1 1 0]
 [0 1 0 0 1 1]
 [0 0 1 1 0 1]]
Проверочная матрица H: 
 [[1 0 1 1 0 0]
 [1 1 0 0 1 0]
 [0 1 1 0 0 1]]


In [ ]:
#Функция для создания порождающей матрицы из проверочной

def create_G_from_H(H):

  r, n = H.shape
  I_k = np.eye(n - r, dtype=int)
  P = H[:, :n - r]
  G = np.concatenate((I_k, P), axis=1)
  return G

# Пример использования:
H = np.array([[1, 1, 0, 1, 0, 0],
              [0, 1, 1, 0, 1, 0],
              [1, 0, 1, 0, 0, 1]])

G = create_G_from_H(H)
print("Проверочная матрица H: \n", H)
print("Порождающая матрица G: \n", G)


Проверочная матрица H: 
 [[1 1 0 1 0 0]
 [0 1 1 0 1 0]
 [1 0 1 0 0 1]]
Порождающая матрица G: 
 [[1 0 0 1 1 0]
 [0 1 0 0 1 1]
 [0 0 1 1 0 1]]


## Задача 2

In [ ]:
#функция создания порождающей матрицы для кода Хэмминга
def create_G_for_hamming_code(r):

  n = 2**r - 1
  k = n - r
  P = np.zeros((k, r), dtype=int)

  for i in range(k):
    binary_representation = bin(i + 1)[2:].zfill(r)
    for j in range(r):
      if binary_representation[j] == '1':
        P[i, j] = 1

  I_k = np.eye(k, dtype=int)
  G = np.concatenate((I_k, P), axis=1)
  return G

# Пример использования:
r = 3
G = create_G_for_hamming_code(r)
print("Порождающая матрица G для кода Хэмминга [7, 4, 3]:\n", G)


Порождающая матрица G для кода Хэмминга [7, 4, 3]:
 [[1 0 0 0 0 0 1]
 [0 1 0 0 0 1 0]
 [0 0 1 0 0 1 1]
 [0 0 0 1 1 0 0]]


In [ ]:
# Функция для кодирования сообщений с помощью порождающей матрицы G
def encode_hamming(message, G):
    return np.dot(message, G) % 2

In [ ]:
import numpy as np
#Функция создания проверочной матрицы H
def create_H_for_hamming_code(r):

  n = 2**r - 1
  H = np.zeros((r, n), dtype=int)
  for i in range(1, n + 1):
    binary_representation = bin(i)[2:].zfill(r)
    for j in range(r):
      H[j, i - 1] = int(binary_representation[j])
  return H

# Пример использования:
r = 3
H = create_H_for_hamming_code(r)
print("Проверочная матрица H для кода Хэмминга [7, 4, 3]:\n", H)

Проверочная матрица H для кода Хэмминга [7, 4, 3]:
 [[0 0 0 1 1 1 1]
 [0 1 1 0 0 1 1]
 [1 0 1 0 1 0 1]]


In [ ]:
# Функция для проверки ошибок с помощью проверочной матрицы H
def check_hamming_errors(codeword, H):
    syndrome = np.dot(codeword, H.T) % 2
    return syndrome

In [ ]:
# Функция для исправления ошибок
def correct_hamming_errors(codeword, H):
    syndrome = check_hamming_errors(codeword, H)
    if np.all(syndrome == 0):
        return codeword

    error_position = int("".join(map(str, syndrome)), 2)
    if error_position > 0:
        codeword[error_position - 1] = (codeword[error_position - 1] + 1) % 2

    return codeword

In [ ]:
# Функция для создания проверочной матрицы из порождающей
def create_hamming_H_from_G(G):
    k, n = G.shape
    P = G[:, k:]
    I_r = np.eye(n - k, dtype=int)
    H = np.concatenate((P.T, I_r), axis=1)
    return H

# Функция для создания порождающей матрицы из проверочной
def create_hamming_G_from_H(H):
    r, n = H.shape
    I_k = np.eye(n - r, dtype=int)
    P = H[:, :n - r]
    G = np.concatenate((I_k, P), axis=1)
    return G

In [ ]:
# Пример использования
r = 3
n = 2**r - 1
k = n - r

# Порождающая матрица G
G = np.array([
    [1, 0, 0, 0, 1, 1, 0],
    [0, 1, 0, 0, 1, 0, 1],
    [0, 0, 1, 0, 0, 1, 1],
    [0, 0, 0, 1, 1, 1, 1]
])

H = create_hamming_H_from_G(G)

message = np.array([1, 0, 1, 1])

encoded_message = encode_hamming(message, G)
print("Закодированное сообщение:", encoded_message)

codeword_with_error = encoded_message.copy()
codeword_with_error[2] = (codeword_with_error[2] + 1) % 2
print("Сообщение с ошибкой:", codeword_with_error)


corrected_codeword = correct_hamming_errors(codeword_with_error, H)
print("Исправленное сообщение:", corrected_codeword)



Закодированное сообщение: [1 0 1 1 0 1 0]
Сообщение с ошибкой: [1 0 0 1 0 1 0]
Исправленное сообщение: [1 0 1 1 0 1 0]
